// Genera public/dict-seed.json en formato jmdict-simplified (subconjunto).
// Seed offline de palabras comunes para el primer arranque, antes de bajar el
// diccionario completo. Glosas en inglés para ser consistente con JMdict-eng.

import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

// [kanji, kana, pos, glosas...]   kanji = "" si es palabra solo-kana
const WORDS = [
  ["日本", "にほん", "n", "Japan"],
  ["日本語", "にほんご", "n", "Japanese language"],
  ["言葉", "ことば", "n", "word", "language", "phrase"],
  ["人", "ひと", "n", "person", "people"],
  ["人々", "ひとびと", "n", "people"],
  ["私", "わたし", "pn", "I", "me"],
  ["今日", "きょう", "n", "today"],
  ["明日", "あした", "n", "tomorrow"],
  ["昨日", "きのう", "n", "yesterday"],
  ["時間", "じかん", "n", "time", "hour"],
  ["年", "とし", "n", "year"],
  ["月", "つき", "n", "month", "moon"],
  ["日", "ひ", "n", "day", "sun"],
  ["水", "みず", "n", "water"],
  ["火", "ひ", "n", "fire"],
  ["大学", "だいがく", "n", "university"],
  ["学校", "がっこう", "n", "school"],
  ["学生", "がくせい", "n", "student"],
  ["先生", "せんせい", "n", "teacher", "doctor"],
  ["会社", "かいしゃ", "n", "company"],
  ["仕事", "しごと", "n", "work", "job"],
  ["駅", "えき", "n", "station"],
  ["電車", "でんしゃ", "n", "train"],
  ["車", "くるま", "n", "car"],
  ["道", "みち", "n", "road", "way", "path"],
  ["店", "みせ", "n", "shop", "store"],
  ["食べ物", "たべもの", "n", "food"],
  ["飲み物", "のみもの", "n", "drink", "beverage"],
  ["ご飯", "ごはん", "n", "cooked rice", "meal"],
  ["肉", "にく", "n", "meat"],
  ["魚", "さかな", "n", "fish"],
  ["野菜", "やさい", "n", "vegetable"],
  ["お茶", "おちゃ", "n", "tea"],
  ["水曜日", "すいようび", "n", "Wednesday"],
  ["名前", "なまえ", "n", "name"],
  ["家", "いえ", "n", "house", "home"],
  ["国", "くに", "n", "country"],
  ["世界", "せかい", "n", "world"],
  ["町", "まち", "n", "town"],
  ["駅前", "えきまえ", "n", "in front of the station"],
  ["手", "て", "n", "hand"],
  ["目", "め", "n", "eye"],
  ["口", "くち", "n", "mouth"],
  ["心", "こころ", "n", "heart", "mind", "spirit"],
  ["お金", "おかね", "n", "money"],
  ["円", "えん", "n", "yen", "circle"],
  ["本", "ほん", "n", "book"],
  ["新聞", "しんぶん", "n", "newspaper"],
  ["写真", "しゃしん", "n", "photograph"],
  ["映画", "えいが", "n", "movie", "film"],
  ["音楽", "おんがく", "n", "music"],
  ["天気", "てんき", "n", "weather"],
  ["雨", "あめ", "n", "rain"],
  ["雪", "ゆき", "n", "snow"],
  ["花", "はな", "n", "flower"],
  ["山", "やま", "n", "mountain"],
  ["川", "かわ", "n", "river"],
  ["海", "うみ", "n", "sea", "ocean"],
  ["空", "そら", "n", "sky"],
  ["朝", "あさ", "n", "morning"],
  ["夜", "よる", "n", "night", "evening"],
  ["問題", "もんだい", "n", "problem", "question"],
  ["意味", "いみ", "n", "meaning"],
  ["質問", "しつもん", "n", "question"],
  ["答え", "こたえ", "n", "answer"],
  ["話", "はなし", "n", "talk", "story"],
  ["元気", "げんき", "adj-na", "healthy", "energetic", "fine"],
  ["大丈夫", "だいじょうぶ", "adj-na", "all right", "OK", "safe"],
  ["有名", "ゆうめい", "adj-na", "famous"],
  ["便利", "べんり", "adj-na", "convenient", "handy"],
  ["大きい", "おおきい", "adj-i", "big", "large"],
  ["小さい", "ちいさい", "adj-i", "small", "little"],
  ["新しい", "あたらしい", "adj-i", "new"],
  ["古い", "ふるい", "adj-i", "old"],
  ["高い", "たかい", "adj-i", "high", "expensive", "tall"],
  ["安い", "やすい", "adj-i", "cheap", "inexpensive"],
  ["良い", "よい", "adj-i", "good"],
  ["悪い", "わるい", "adj-i", "bad"],
  ["難しい", "むずかしい", "adj-i", "difficult"],
  ["易しい", "やさしい", "adj-i", "easy", "plain"],
  ["楽しい", "たのしい", "adj-i", "fun", "enjoyable"],
  ["面白い", "おもしろい", "adj-i", "interesting", "amusing"],
  ["多い", "おおい", "adj-i", "many", "numerous"],
  ["少ない", "すくない", "adj-i", "few", "scarce"],
  ["食べる", "たべる", "v1", "to eat"],
  ["飲む", "のむ", "v5m", "to drink"],
  ["見る", "みる", "v1", "to see", "to look", "to watch"],
  ["聞く", "きく", "v5k", "to hear", "to listen", "to ask"],
  ["読む", "よむ", "v5m", "to read"],
  ["書く", "かく", "v5k", "to write"],
  ["話す", "はなす", "v5s", "to speak", "to talk"],
  ["言う", "いう", "v5u", "to say", "to tell"],
  ["行く", "いく", "v5k", "to go"],
  ["来る", "くる", "vk", "to come"],
  ["帰る", "かえる", "v5r", "to return", "to go home"],
  ["する", "する", "vs-i", "to do"],
  ["なる", "なる", "v5r", "to become"],
  ["ある", "ある", "v5r", "to exist (inanimate)", "to have"],
  ["いる", "いる", "v1", "to exist (animate)", "to be present"],
  ["買う", "かう", "v5u", "to buy"],
  ["使う", "つかう", "v5u", "to use"],
  ["作る", "つくる", "v5r", "to make", "to create"],
  ["思う", "おもう", "v5u", "to think", "to feel"],
  ["知る", "しる", "v5r", "to know"],
  ["分かる", "わかる", "v5r", "to understand", "to know"],
  ["勉強", "べんきょう", "vs", "study"],
  ["大切", "たいせつ", "adj-na", "important", "precious"],
  ["", "とても", "adv", "very", "extremely"],
  ["", "たくさん", "adv", "a lot", "many"],
  ["全部", "ぜんぶ", "n", "all", "entire"],
  ["少し", "すこし", "adv", "a little", "a bit"],
  ["今", "いま", "n", "now"],
  ["時", "とき", "n", "time", "moment"],
  ["所", "ところ", "n", "place", "spot"],
];

function buildWord(entry, i) {
  const [kanji, kana, pos, ...glosses] = entry;
  return {
    id: `seed-${i + 1}`,
    kanji: kanji ? [{ text: kanji, common: true, tags: [] }] : [],
    kana: [{ text: kana, common: true, tags: [], appliesToKanji: ["*"] }],
    sense: [
      {
        partOfSpeech: [pos],
        appliesToKanji: ["*"],
        appliesToKana: ["*"],
        gloss: glosses.map((text) => ({
          lang: "eng",
          gender: null,
          type: null,
          text,
        })),
      },
    ],
  };
}

const file = {
  version: "seed-1",
  languages: ["eng"],
  commonOnly: true,
  words: WORDS.map(buildWord),
};

const here = dirname(fileURLToPath(import.meta.url));
const dest = resolve(here, "../public/dict-seed.json");
await writeFile(dest, JSON.stringify(file), "utf8");
console.log(`[build-seed] ${file.words.length} palabras -> public/dict-seed.json`);
